### PR TITLE
macOS 2nd try

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hello @simonjwrigth, rebased the macOS support on the fresh refactoring that I did for Windows builds.

It still fails, but with a different error this time:
```
 build/genmddeps ../../src/gcc/common.md ../../src/gcc/config/i386/i386.md > tmp-mddeps
dyld: Symbol not found: __ZdlPvm
  Referenced from: /Users/runner/work/GNAT-FSF-builds/GNAT-FSF-builds/sbx/x86_64-darwin/gcc/build/gcc/build/genmddeps
  Expected in: /usr/lib/libstdc++.6.dylib
 in /Users/runner/work/GNAT-FSF-builds/GNAT-FSF-builds/sbx/x86_64-darwin/gcc/build/gcc/build/genmddeps
```
It looks like `genmddeps` is an executable. I have the exact same error on my machine.

Is the build procedure that you are using for https://sourceforge.net/projects/gnuada/files/GNAT_GCC%20Mac%20OS%20X/ available?
I would like to reproduce the build on my machine to see how it works, what are the options, etc.

Thanks,

**Comment by simonjwright** [comment]
Hi @Fabien-Chouteau - I would’ve noticed this sooner if you’d used the right handle for me!!! Never mind, here now ...

**Comment by simonjwright** [comment]
As to how I do the FSF builds at SF, see [here](https://github.com/simonjwright/building-gcc-macos-native/tree/gnat-ce-2021) - that’s as used for my upcoming GNAT CE 2021 build, and is what I’ll base the next FSF build on. The `gcc-11.1.0` tag doesn’t have `--with-build-sysroot=` & friends, so  I have to ask people to define `SDKROOT=$(xcrun --show-sdk-path)`.

It looks as though the GNAT build worked fine: the differences I see from mine are
* you have kept the --with-specs lines (twice), whereas I never saw any result from using them at all.
* I’ve added `--with-build-config=no` (can’t at this moment remember why :)
* I need to add to add the `--with-*-ldflags` options because I need the `-Wl,-headerpad_max_install_names` options so I can mess with dylibs; I haven’t checked recently, but at the point when I started using that, using `--with-*-ldflags` at all would stop you getting a static build, with the result that unless you specified `-static-libstdc++ -static-libgcc` _as well_ you’d find yourself picking up the wrong `libstdc++`, as you found. Anyway, after all that, if you leave the switch out the build goes OK.

I think the problem with gprbuild is that you’re using v21.0.0, and you need [this change](https://github.com/AdaCore/gprbuild/commit/0b775473a8eb5f820f487869d31ac534a437826c).

**Comment by Fabien-Chouteau** [comment]
Hi @simonjwright 

> As to how I do the FSF builds at SF, see [here](https://github.com/simonjwright/building-gcc-macos-native/tree/gnat-ce-2021) - that’s as used for my upcoming GNAT CE 2021 build, and is what I’ll base the next FSF build on.

Thanks for the link I will have a look.

> `  The `gcc-11.1.0` tag doesn’t have `--with-build-sysroot=` & friends, so I have to ask people to define `SDKROOT=$(xcrun --show-sdk-path)`.

Do you know why they removed that?
 
> It looks as though the GNAT build worked fine:

Yeah, I finally got it working be removing options one by one. `--with-stage1-ldflags=-static-libstdc++` and `--with-boot-ldflags=-static-libstdc++` were the problem. I copied those from the last GNAT CE on macOS...

> the differences I see from mine are
>     * you have kept the --with-specs lines (twice), whereas I never saw any result from using them at all.

I removed it in my last attempts (not pushed to the repo yet).

>     * I’ve added `--with-build-config=no` (can’t at this moment remember why :)

Maybe related to this: https://github.com/Homebrew/homebrew-core/blob/98064198c7e5464124f53bbdb47bec3e03f1a0cd/Formula/gcc.rb#L101


>     * I need to add to add the `--with-*-ldflags` options because I need the `-Wl,-headerpad_max_install_names` options so I can mess with dylibs; I haven’t checked recently, but at the point when I started using that, using `--with-*-ldflags` at all would stop you getting a static build, with the result that unless you specified `-static-libstdc++ -static-libgcc` _as well_ you’d find yourself picking up the wrong `libstdc++`, as you found. Anyway, after all that, if you leave the switch out the build goes OK.

Homebrew does it a different way: https://github.com/Homebrew/homebrew-core/blob/98064198c7e5464124f53bbdb47bec3e03f1a0cd/Formula/gcc.rb#L136

> I think the problem with gprbuild is that you’re using v21.0.0, and you need [this change](https://github.com/AdaCore/gprbuild/commit/0b775473a8eb5f820f487869d31ac534a437826c).

Indeed, I will apply just this patch to `20.0.0`.

Thanks for your help :)

**Comment by simonjwright** [comment]
> Hi @simonjwright

Sorry, I replied to this earlier but obvs forgot to hit 'Comment'.

> > ` The`gcc-11.1.0`tag doesn’t have`--with-build-sysroot=`& friends, so I have to ask people to define`SDKROOT=$(xcrun --show-sdk-path)`.
> 
> Do you know why they removed that?

I’d never put it in

I’ve now got `--with-specs=` working. My problem was that `-dumpspecs` shows no sign of this!

Just fyi, using `--with-sysroot=/foo/bar` means that `$prefix/include` isn’t included in the standard search path. The documentation says that `--with-sysroot` is really intended for cross-compilers, and `--with-build-sysroot` only applies if `--with-sysroot` is given - clearly *not* true!

> > I think the problem with gprbuild is that you’re using v21.0.0, and you need [this change](https://github.com/AdaCore/gprbuild/commit/0b775473a8eb5f820f487869d31ac534a437826c).
> 
> Indeed, I will apply just this patch to `20.0.0`.

I actually meant the patch should be applied to 21.0.0.

**Comment by Fabien-Chouteau** [comment]
Almost there @simonjwright, only the `gnatcov` build is failing because the gnu binutils are used for the compilation (I think).

**Comment by simonjwright** [comment]
As with the native GCC compiler build, you have to use the native binutils (such as they are) to build a native executable. Some of the tricks that GNU binutils can do can’t be done with Mach-O: in particular, [the fiddles needed to make stand-alone static libraries](https://github.com/AdaCore/gprbuild/issues/97). Not sure what gnatcov might need?

I’ve not come across gnatcov before, looks impressive! Are you only intending the Alire version to be for the native target?

**Comment by Fabien-Chouteau** [comment]
@simonjwright gnatcov needs the binutils but they should not be in PATH, that was my mistake. It's all good now :)

**Pull request merged**
